# Generated by Django 4.0.3 on 2022-03-19 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('tipo_id', models.CharField(choices=[('ID', 'Cédula de Identidad'), ('L', 'Licencia de Conducir'), ('P', 'Pasaporte')], max_length=3)),
                ('numero_id', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.IntegerField()),
                ('baño_privado', models.BooleanField(null=True)),
                ('tamaño_cama', models.CharField(choices=[('M', 'Matrimonial'), ('KS', 'King Size'), ('S', 'Simple')], max_length=2, null=True)),
                ('aire_acondicionado', models.BooleanField(null=True)),
                ('precio', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiasReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESERVAS.cuarto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Pagado'), ('E', 'Eliminado')], max_length=1)),
                ('metodo_pago', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta'), ('R', 'Transferencia')], max_length=3)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='RESERVAS.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESERVAS.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nit', models.BigIntegerField(blank=True, null=True)),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESERVAS.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveBigIntegerField()),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESERVAS.cuarto')),
                ('dias', models.ManyToManyField(to='RESERVAS.diasreserva')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESERVAS.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'cuarto')},
            },
        ),
    ]
