# Generated by Django 4.0.3 on 2022-03-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0002_remove_diasreserva_cuarto_habitacion_dias_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='reservado',
            field=models.BooleanField(null=True),
        ),
    ]
