# Generated by Django 4.0.3 on 2022-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0003_habitacion_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='dias_reservado',
            field=models.ManyToManyField(blank=True, null=True, to='RESERVAS.diasreserva'),
        ),
    ]
