# Generated by Django 4.0.3 on 2022-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0005_alter_habitacion_dias_reservado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaitem',
            name='dias',
        ),
        migrations.AddField(
            model_name='reservaitem',
            name='dias',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
