# Generated by Django 4.0.3 on 2022-03-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0006_remove_reservaitem_dias_reservaitem_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaitem',
            name='precio',
        ),
    ]
