# Generated by Django 4.0.3 on 2022-03-21 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0008_remove_habitacion_dias_reservado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
