# Generated by Django 4.0.3 on 2022-03-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0009_factura_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
