# Generated by Django 4.0.3 on 2022-03-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0010_habitacion_fecha_final_habitacion_fecha_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaitem',
            name='dias',
        ),
    ]
