# Generated by Django 4.0.3 on 2022-03-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0012_alter_factura_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='fecha_inicial',
        ),
        migrations.AddField(
            model_name='reservaitem',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaitem',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
