# Generated by Django 4.0.3 on 2022-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0013_remove_habitacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaitem',
            name='dias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
