# Generated by Django 4.0.3 on 2022-03-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0014_reservaitem_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reservaitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservaitem',
            name='cuarto',
        ),
        migrations.RemoveField(
            model_name='reservaitem',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='servicioadicional',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='bloque',
        ),
        migrations.DeleteModel(
            name='Bloque',
        ),
        migrations.DeleteModel(
            name='ReservaItem',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ServicioAdicional',
        ),
        migrations.AddField(
            model_name='booking',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESERVAS.habitacion'),
        ),
    ]
