# Generated by Django 4.0.3 on 2022-03-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0015_booking_alter_reservaitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='aire_acondicionado',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='baño_privado',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='numero_habitacion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='tamaño_cama',
        ),
        migrations.AddField(
            model_name='booking',
            name='reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='RESERVAS.reserva'),
            preserve_default=False,
        ),
    ]
