# Generated by Django 4.0.3 on 2022-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0016_remove_habitacion_aire_acondicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
