# Generated by Django 4.0.3 on 2022-03-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0017_habitacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_id',
            field=models.CharField(blank=True, choices=[('ID', 'Cédula de Identidad'), ('L', 'Licencia de Conducir'), ('P', 'Pasaporte')], max_length=3, null=True),
        ),
    ]
