# Generated by Django 4.0.3 on 2022-03-24 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0022_alter_cliente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='RESERVAS/images')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESERVAS.habitacion')),
            ],
        ),
    ]
