# Generated by Django 4.0.3 on 2022-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0024_alter_imagenhabitacion_habitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
