# Generated by Django 4.0.3 on 2022-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESERVAS', '0025_habitacion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='aire_acondicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['nombre'], name='RESERVAS_ha_nombre_b15dde_idx'),
        ),
    ]
